#!/usr/bin/env bash
# on web server, commands to install nginx

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

# testing nginx configuration
sudo nginx -t

sudo service nginx reload
